services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - .env
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - wordpress:/var/www/html
    expose:
      - "9000"
    env_file:
      - .env
    networks:
      - inception
    restart: always
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - .env
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      device: /Users/johyeongeun/42/inception/srcs/wordpress
#      device: /home/hyungcho/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver_opts:
      device: /Users/johyeongeun/42/inception/srcs/mariadb
#      device: /home/hyungcho/data/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge